CREATE TABLE "workout-tracker_exercise" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"name" varchar(256) NOT NULL,
	"muscleGroup" varchar(64) NOT NULL,
	"description" text NOT NULL,
	"tutorialUrl" varchar(512),
	"imageUrl" varchar(512)
);
--> statement-breakpoint
CREATE TABLE "workout-tracker_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "workout-tracker_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "muscle_group_idx" ON "workout-tracker_exercise" USING btree ("muscleGroup");--> statement-breakpoint
CREATE INDEX "name_idx" ON "workout-tracker_post" USING btree ("name");